# Generated by Django 2.0.8 on 2019-07-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190703_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(default=0, related_name='categories', to='posts.Category'),
        ),
    ]
